name: "Публикация пакета"

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Публикация пакета
    runs-on: ubuntu-latest
    steps:
      - name: Сheckout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.JS
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org
      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}